"""add_multi_problem_columns

Revision ID: 689f2dbf6ac7
Revises: 3ad67c4dc4ed
Create Date: 2026-07-04 15:47:03.354288
"""

from alembic import op
import sqlalchemy as sa



revision = '689f2dbf6ac7'
down_revision = '3ad67c4dc4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_players', sa.Column('progress', sa.Text(), nullable=True))
    op.add_column('battle_players', sa.Column('active_problem_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('battles', sa.Column('selected_slugs', sa.Text(), nullable=True))
    op.add_column('battles', sa.Column('custom_problems', sa.Text(), nullable=True))
    op.add_column('battles', sa.Column('problem_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'problem_ids')
    op.drop_column('battles', 'custom_problems')
    op.drop_column('battles', 'selected_slugs')
    op.drop_column('battle_players', 'active_problem_index')
    op.drop_column('battle_players', 'progress')
    # ### end Alembic commands ###
