import type { ProblemListItem, Tag, Paginated, LeaderboardEntry } from './api';

export const MOCK_TAGS: Tag[] = [
  { id: 'tag-1', name: 'Arrays' },
  { id: 'tag-2', name: 'Math' },
  { id: 'tag-3', name: 'Dynamic Programming' },
  { id: 'tag-4', name: 'Recursion' },
  { id: 'tag-5', name: 'Two Pointers' },
  { id: 'tag-6', name: 'Binary Search' },
  { id: 'tag-7', name: 'Graph' },
  { id: 'tag-8', name: 'Sorting' },
];

export const MOCK_PROBLEMS: ProblemListItem[] = [
  {
    id: 'prob-1',
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'EASY',
    acceptance_rate: 48.3,
    score_base: 100,
    tags: [MOCK_TAGS[0], MOCK_TAGS[1]],
    is_published: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'prob-2',
    slug: 'longest-substring-without-repeating',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'MEDIUM',
    acceptance_rate: 33.7,
    score_base: 200,
    tags: [MOCK_TAGS[4]],
    is_published: true,
    created_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 'prob-3',
    slug: 'median-of-two-sorted-arrays',
    title: 'Median of Two Sorted Arrays',
    difficulty: 'HARD',
    acceptance_rate: 37.1,
    score_base: 400,
    tags: [MOCK_TAGS[0], MOCK_TAGS[5]],
    is_published: true,
    created_at: '2026-01-14T00:00:00Z',
  },
  {
    id: 'prob-4',
    slug: 'climbing-stairs',
    title: 'Climbing Stairs',
    difficulty: 'EASY',
    acceptance_rate: 51.8,
    score_base: 100,
    tags: [MOCK_TAGS[2], MOCK_TAGS[3]],
    is_published: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prob-5',
    slug: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'MEDIUM',
    acceptance_rate: 54.2,
    score_base: 200,
    tags: [MOCK_TAGS[4], MOCK_TAGS[0]],
    is_published: true,
    created_at: '2026-01-16T00:00:00Z',
  },
  {
    id: 'prob-6',
    slug: 'reverse-linked-list',
    title: 'Reverse Linked List',
    difficulty: 'EASY',
    acceptance_rate: 73.1,
    score_base: 100,
    tags: [],
    is_published: true,
    created_at: '2026-01-17T00:00:00Z',
  },
  {
    id: 'prob-7',
    slug: 'binary-tree-inorder-traversal',
    title: 'Binary Tree Inorder Traversal',
    difficulty: 'EASY',
    acceptance_rate: 74.5,
    score_base: 100,
    tags: [MOCK_TAGS[6]],
    is_published: true,
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: 'prob-8',
    slug: 'merge-k-sorted-lists',
    title: 'Merge k Sorted Lists',
    difficulty: 'HARD',
    acceptance_rate: 47.6,
    score_base: 400,
    tags: [MOCK_TAGS[6], MOCK_TAGS[7]],
    is_published: true,
    created_at: '2026-01-19T00:00:00Z',
  },
  {
    id: 'prob-9',
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'HARD',
    acceptance_rate: 57.0,
    score_base: 400,
    tags: [MOCK_TAGS[0], MOCK_TAGS[4]],
    is_published: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prob-10',
    slug: 'coin-change',
    title: 'Coin Change',
    difficulty: 'MEDIUM',
    acceptance_rate: 41.3,
    score_base: 200,
    tags: [MOCK_TAGS[2]],
    is_published: true,
    created_at: '2026-01-21T00:00:00Z',
  },
];

export const MOCK_PAGINATED_PROBLEMS: Paginated<ProblemListItem> = {
  items: MOCK_PROBLEMS,
  total: MOCK_PROBLEMS.length,
  page: 1,
  limit: 20,
  pages: 1,
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, username: 'alice_dev',    score: 3400, solved: 12 },
  { rank: 2, username: 'bob_codes',    score: 2900, solved: 10 },
  { rank: 3, username: 'charlie_xyz',  score: 2400, solved: 8  },
  { rank: 4, username: 'diana_algo',   score: 1800, solved: 6  },
  { rank: 5, username: 'evan_123',     score: 1200, solved: 4  },
  { rank: 6, username: 'frank_bits',   score:  900, solved: 3  },
  { rank: 7, username: 'grace_loop',   score:  600, solved: 2  },
  { rank: 8, username: 'henry_stack',  score:  300, solved: 1  },
];
